#!/usr/bin/env python3

#This script uses the Ensembl VEP REST API to annotate variants in the TSV file generated by
#extract_variants.sh.

#This produces a complete annotation with one row per transcript.

#Use: python3 vep_rest_annotation_complete.py <input_tsv> <output_tsv> <sample_id>

#====================Import libraries===================
import sys
    #for command line arguments
import requests 
    #for the VEP REST API calls
import pandas as pd 
    #for data manipulation and writing output TSV

#====================Variables===================

VARIANTS_TSV = sys.argv[1]
ANNOTATED_TSV = sys.argv[2]
SAMPLE_ID = sys.argv[3]

#====================Read input TSV===================

variants_dataframe = pd.read_csv(VARIANTS_TSV, sep='\t')

#====================Prepare variant dataframe for VEP===================

#Empty list to hold variant strings in the format
#expected by the VEP REST API
variants = []

#Iterate over each row in the variants dataframe
for index, row in variants_dataframe.iterrows():

    #Extract the fields for each variant
    chrom = row['CHROM']
    pos = row['POS']
    variant_id = row['ID']
    ref = row['REF']
    alt_field = row['ALT']
    qual = row['QUAL']
    genotype = row['GENOTYPE']
    phase_set = row['PHASE_SET']

    #The ALT field may contain multiple alleles separated by commas
    alt_alleles = str(alt_field).split(',')

    #Iterate over each alternate allele
    for alt in alt_alleles:

        #Build the input variant format needed for the VEP REST API: "chrom pos id ref alt"
        input_variant = f"{chrom} {pos} {variant_id} {ref} {alt}"

        variants.append({
            "sample_id": SAMPLE_ID,
            "chrom": chrom,
            "pos": pos,
            "id": variant_id,
            "ref": ref,
            "alt_original": alt_field,
            "alt_annotated": alt,
            "qual": qual,
            "genotype": genotype,
            "phase_set": phase_set,
            "input_variant": input_variant
        })

#===================Call VEP REST API to annotate variants===================

#Define the url and endoint
server = "https://rest.ensembl.org"

endpoint = "/vep/homo_sapiens/region"

#Define the params
params = {
    "pick_allele": 1,
    "symbol": 1,
    "hgvs": 1,
    "canonical": 1,
    "mane": 1,
    "variant_class": 1,
    "vcf_string": 1
}

#Convert the variant dictionary list in a string list
variant_list = []

for variant in variants:
    variant_list.append(variant["input_variant"])

headers = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

#Define the maximum number of variants per request
batch_size = 200

#Empty list to store all VEP responses
data = []

#Send the variants in batches
for start in range(0, len(variant_list), batch_size):
    end = start + batch_size
    batch = variant_list[start:end]

    payload = {
        "variants": batch
    }

    response = requests.post(
        server + endpoint,
        headers=headers,
        params=params,
        json=payload
    )

    print(f"Processing variants {start} to {end - 1}")
    print("Status code:", response.status_code)

    response.raise_for_status()

    batch_data = response.json()
    data.extend(batch_data)

#=====================Write annotated variants to output TSV===================

#Create a dictionary to look for the original variant information
variant_look = {}

#Recover the information of the original variants
for variant in variants:
    variant_look[variant["input_variant"]] = variant

#Empty list to store the annotated rows
rows = []

#Iterate over the VEP response
for variant_entry in data:

    input_variant = variant_entry.get("input")
    original_info = variant_look[input_variant]
    table = variant_entry.get("transcript_consequences", []) or []

    if table:
        for transcript in table:
            rows.append({
                "sample_id": SAMPLE_ID,
                "CHROM": original_info["chrom"],
                "POS": original_info["pos"],
                "ID": original_info["id"],
                "REF": original_info["ref"],
                "ALT_original": original_info["alt_original"],
                "ALT_annotated": original_info["alt_annotated"],
                "QUAL": original_info["qual"],
                "GENOTYPE": original_info["genotype"],
                "PHASE_SET": original_info["phase_set"],
                "input_variant": input_variant,
                "variant_class": variant_entry.get("variant_class"),
                "most_severe_consequence": variant_entry.get("most_severe_consequence"),
                "gene": transcript.get("gene_symbol"),
                "transcript": transcript.get("transcript_id"),
                "consequence": ",".join(transcript.get("consequence_terms", [])) if transcript.get("consequence_terms") else None,
                "impact": transcript.get("impact"),
                "hgvs_c": transcript.get("hgvsc"),
                "hgvs_p": transcript.get("hgvsp"),
                "MANE": transcript.get("mane_select"),
                "canonical": transcript.get("canonical"),
                "exon": transcript.get("exon"),
                "biotype": transcript.get("biotype"),
                "variant_allele": transcript.get("variant_allele"),
            })

#Transform the list of annotated rows into a dataframe
annotated_variants_df = pd.DataFrame(rows)

#Write the annotated variants to the output TSV
annotated_variants_df.to_csv(ANNOTATED_TSV, sep='\t', index=False)