#!/usr/bin/env python3

#This script summarizes coverage gaps from a tsv file generated by detect_coverage_gaps.py

#Use: python summarize_coverage_gaps.py <input_gap_tsv> <output_summary_tsv> 


###########################
####### PREPARATION #######
###########################

#Import necessary libraries
import os
import sys

#Define input arguments
input_gap_tsv = sys.argv[1] # Path to the TSV file with detected coverage gaps
output_summary_tsv = sys.argv[2] # Path to save the output summary TSV

#Create outpout directory if it doesn't exist
output_dir = os.path.dirname(output_summary_tsv)
os.makedirs(output_dir, exist_ok=True)


###########################
###### READING INPUT ######
###########################

#Preparing empty variables to store gap data and metadata
gap_data = [] #List to store gap data for summarization
sample_name = None #Variable to store the sample name
threshold = None #Variable to store the coverage threshold

#Open the input TSV file and read the gap data
with open(input_gap_tsv, "r") as f:
    header = f.readline().strip().split("\t") # Read the header line
    for line in f: #Read each line in the file
        fields = line.strip().split("\t") #Split the line into fields based on tab separation
        
        #Create a dictionary for the current row 
        row = dict(zip(header, fields)) #Using the header and fields to create the dictionary
        #Convert numeric fields to integers
        row["gap_start"] = int(row["gap_start"]) 
        row["gap_end"] = int(row["gap_end"]) 
        row["gap_length"] = int(row["gap_length"]) 
        row["threshold"] = int(row["threshold"]) 
        
        gap_data.append(row) # Append the row dictionary to the gap_data list

        #Extract sample name and threshold from the first row (assuming they are consistent across all rows)
        if sample_name is None:
            sample_name = row["sample"]
        if threshold is None:
            threshold = row["threshold"]


###########################
###### GLOBAL SUMMARY #####
###########################

#Calculate global summary statistics for the detected gaps
total_gaps = len(gap_data) #Total number of gaps detected
total_gap_bases = sum(row["gap_length"] for row in gap_data) #Total length of all gaps

#Calculate average gap length
if total_gaps > 0:
    average_gap_length = round(total_gap_bases / total_gaps, 3)
else:
    average_gap_length = 0

#Calculate gaps longer than differente size thresholds
gaps_over_10bp = 0 
gaps_over_100bp = 0
gaps_over_1000bp = 0
gaps_over_10000bp = 0

for row in gap_data:
    if row["gap_length"] > 10:
        gaps_over_10bp += 1
    if row["gap_length"] > 100:
        gaps_over_100bp += 1
    if row["gap_length"] > 1000:
        gaps_over_1000bp += 1
    if row["gap_length"] > 10000:
        gaps_over_10000bp += 1

#Calculate the max gap length
if total_gaps > 0:
    max_gap_length = max(row["gap_length"] for row in gap_data)
else:
    max_gap_length = 0

#Prepare the summary data as a dictionary for output
summary_data = {
    "threshold": threshold,
    "total_gaps": total_gaps,
    "total_gap_bases": total_gap_bases,
    "average_gap_length": average_gap_length,
    "gaps_over_10bp": gaps_over_10bp,
    "gaps_over_100bp": gaps_over_100bp,
    "gaps_over_1000bp": gaps_over_1000bp,
    "gaps_over_10000bp": gaps_over_10000bp,
    "max_gap_length": max_gap_length
}


###########################
#### CHROM SUMMARY ########
###########################

#Group gaps by chromosome
gaps_by_chrom = {}

for row in gap_data: #Iterate through each row in the gap data
    chrom = row["chrom"] #Extract the chromosome name from the row

    #Add the row to the chromosome group in gaps_by_chrom dictionary
    if chrom not in gaps_by_chrom: 
        gaps_by_chrom[chrom] = []

    #Add the current row to the list of gaps for each chromosome
    gaps_by_chrom[chrom].append(row) 

#Dictionary to store summary data for each chromosome
chrom_summary_data = {} 

#Calculate summary statistics for each chromosome
#For loop to calculate statistics for each chromosome
for chrom, chrom_gaps in gaps_by_chrom.items():

    #Calculate total gaps and total gap bases for the chromosome
    chrom_total_gaps = len(chrom_gaps)
    chrom_total_gap_bases = sum(row["gap_length"] for row in chrom_gaps)

    #Calculate average gap length
    if chrom_total_gaps > 0:
        chrom_average_gap_length = round(chrom_total_gap_bases / chrom_total_gaps, 3)
    else:
        chrom_average_gap_length = 0
    
    #Calculate the max gap length for the chromosome
    if chrom_total_gaps > 0:
        chrom_max_gap_length = max(row["gap_length"] for row in chrom_gaps)
    else:
        chrom_max_gap_length = 0

    #Calculate gaps longer than different size thresholds for the chromosome
    chrom_gaps_over_10bp = 0 
    chrom_gaps_over_100bp = 0
    chrom_gaps_over_1000bp = 0
    chrom_gaps_over_10000bp = 0

    for row in chrom_gaps:
        if row["gap_length"] > 10:
            chrom_gaps_over_10bp += 1
        if row["gap_length"] > 100:
            chrom_gaps_over_100bp += 1
        if row["gap_length"] > 1000:
            chrom_gaps_over_1000bp += 1
        if row["gap_length"] > 10000:
            chrom_gaps_over_10000bp += 1

    #Store the summary data for the chromosome in the chrom_summary_data dictionary
    chrom_summary_data[chrom] = {
        "total_gaps": chrom_total_gaps,
        "total_gap_bases": chrom_total_gap_bases,
        "average_gap_length": chrom_average_gap_length,
        "max_gap_length": chrom_max_gap_length,
        "gaps_over_10bp": chrom_gaps_over_10bp,
        "gaps_over_100bp": chrom_gaps_over_100bp,
        "gaps_over_1000bp": chrom_gaps_over_1000bp,
        "gaps_over_10000bp": chrom_gaps_over_10000bp
    }


###########################
### WRITE SUMMARY OUTPUT ###
########################### 

with open(output_summary_tsv, "w") as out:
    
    #Global summary section
    out.write(f"#Summary of coverage gaps for sample {sample_name} with threshold {threshold}\n")
    out.write("#Global metrics for coverage gaps\n")
    out.write("section\tsample\tmetric\tvalue\n") #Header
    #Write each metric and its value
    for metric, value in summary_data.items():
        out.write(f"@GLOBAL\t{sample_name}\t{metric}\t{value}\n")

    #Chromosome summary section
    out.write("\n")
    out.write("#Chromosome by chromosome metrics for coverage gaps\n")
    out.write("section\tsample\tchromosome\ttotal_gaps\ttotal_gap_bases\taverage_gap_length\tmax_gap_length\tgaps_over_10bp\tgaps_over_100bp\tgaps_over_1000bp\tgaps_over_10000bp\n")

    for chrom, chrom_data in chrom_summary_data.items():
        out.write(
            f"@CHROM\t{sample_name}\t{chrom}\t"
            f"{chrom_data['total_gaps']}\t"
            f"{chrom_data['total_gap_bases']}\t"
            f"{chrom_data['average_gap_length']}\t"
            f"{chrom_data['max_gap_length']}\t"
            f"{chrom_data['gaps_over_10bp']}\t"
            f"{chrom_data['gaps_over_100bp']}\t"
            f"{chrom_data['gaps_over_1000bp']}\t"
            f"{chrom_data['gaps_over_10000bp']}\n"
        )


###########################
######## FINISHING ########
########################### 

#Info message of finished summarization process
print(f"Coverage gap summary generated and saved to {output_summary_tsv}")